Model, Deployment and Passport Management Modules
AI4HF/passport-web pull request #16
Opened 2024-08-05 10:12 UTC by KeremHmd

Three new modules are implemented with required edits to the existing tools and form refactors.

2024-08-06 08:32 UTC, Okanmercan99 requested changes

2024-08-06 08:32 UTC, Okanmercan99 commented on src/app/modules/dataset-management/dataset-management-edit/learning-dataset-creation/learning-dataset-creation-table/learning-dataset-creation-table.component.ts
>      /** The selected dataset */
Let's correct comment here.

2024-08-06 08:32 UTC, Okanmercan99 commented on src/app/modules/deployment-management/deployment-management-edit/model-deployment-details/model-deployment-details.component.ts
> +   * Load model deployment by environmentId
Let's correct comment here.

2024-08-06 08:32 UTC, Okanmercan99 commented on src/app/modules/passport-management/passport-management-form/passport-management-form.component.ts
> +    modelNameList: any[];
Let's create a class for modelName.

2024-08-06 08:32 UTC, Okanmercan99 commented on src/app/modules/passport-management/passport-management-form/passport-management-form.component.ts
> +            modelDeployment.modelName = model ? model.name : '';
Let's correct boolean expression.

2024-08-06 08:32 UTC, Okanmercan99 commented on src/app/modules/passport-management/passport-management-table/passport-management-table.component.ts
> +  passportWithModelNameList: any[];
Let's create a class and use it, instead of any.

2024-08-06 08:32 UTC, Okanmercan99 commented on src/app/modules/passport-management/passport-management-table/passport-management-table.component.ts
> +  modelList: any[];
Let's refactor any here.

2024-08-06 08:32 UTC, Okanmercan99 commented on src/app/modules/passport-management/passport-management-table/passport-management-table.component.ts
> +            passport.modelName = model ? model.name : '';
Let's correct boolean expression.

2024-08-06 08:32 UTC, Okanmercan99 commented on src/app/modules/study-management/study-management-edit/study-details/study-details.component.ts
> +      console.log(this.studyForm.value.name);
Let's remove console.log here.

2024-08-07 07:16 UTC, Okanmercan99 approved these changes

2024-08-07 13:24 UTC, dogukan10 approved these changes

2024-08-07 13:24 UTC, merged