Learning Process Management
AI4HF/passport-web pull request #17
Opened 2024-08-15 06:35 UTC by KeremHmd

Learning Process Management Frontend Implementation, along with some fixes to previous modules' problems.

2024-08-19 08:04 UTC, Okanmercan99 requested changes

2024-09-05 07:12 UTC, dogukan10 commented
There are a few files that start with "ls" and "lp," and I think it would improve clarity if we explicitly rename them to "learning-stage" and "learning-process." While the names would be longer, they would make the code more understandable.

If @Okanmercan99  agree with this approach, @KeremHmd, could you please update the file and class names accordingly?

2024-09-05 07:22 UTC, dogukan10 approved these changes

2024-09-05 07:26 UTC, Okanmercan99 approved these changes

2024-09-05 07:26 UTC, merged