Multiple Role Authorization
AI4HF/passport-web pull request #25
Opened 2024-12-04 12:19 UTC by KeremHmd

- Study-Based Authorization Integration
- Page hierarchy updates with respect to the newly adopted role relations.
- ML_ENGINEER Introduction
- Role-Based Authorization Updates

2024-12-06 08:18 UTC, Okanmercan99 requested changes

2024-12-25 11:38 UTC, Okanmercan99 commented
![image](https://github.com/user-attachments/assets/5aa41f40-170f-4a3a-9019-c90bfb305924)
Let's rename "Is Study Owner" as "Set As Study Owner". Also move it into end of the form (after email).

2024-12-25 11:46 UTC, Okanmercan99 commented
![image](https://github.com/user-attachments/assets/be174b4c-d9c8-49ea-9036-99150f8b94fa)
Let's move down this submenu. Data Scientist should be readable.

2024-12-25 12:15 UTC, Okanmercan99 requested changes

2024-12-25 12:15 UTC, Okanmercan99 commented on src/app/core/services/role.service.ts
> +            return "No Active Roles";
Let's use translate module in here.

2024-12-26 10:40 UTC, Okanmercan99 approved these changes

2025-01-02 10:25 UTC, dogukan10 commented on src/app/modules/featureset-management/featureset-management-edit/featureset-features/featureset-features-table/featureset-features-table.component.ts
> +        this.featureService.deleteFeature(featureId, +this.activeStudyService.getActiveStudy()).pipe(takeUntil(this.destroy$))
Instead of using the unary `+` operator to convert a string to a number, we can accept the study ID as a string directly. This change would make the code more readable and easier to understand.

2025-01-02 10:25 UTC, dogukan10 commented on src/app/modules/not-found-page/not-found-page.component.html
> +<style>
Let's move this style to scss file.

2025-01-29 13:51 UTC, merged