Edit study
AI4HF/passport-web pull request #5
Opened 2024-06-24 10:27 UTC by Okanmercan99

2024-06-25 11:54 UTC, dogukan10 requested changes

2024-06-25 11:54 UTC, dogukan10 commented on src/app/shared/components/stepper/stepper.module.ts
> +export class StepperModule { }
I think that this module is redundant because we define it under shared folder so that I expect that it should be a part of the Shared Module. WDYT ?

2024-06-25 11:54 UTC, dogukan10 commented on src/app/modules/study-management/study-management-edit/population-details/population-details.module.ts
> +export class PopulationDetailsModule { }
I think that there is no need to define a separate module for each folder under study-management-edit folder. We can simply add these component to StudyManagementEditModule ?

2024-06-25 11:54 UTC, dogukan10 commented on src/app/modules/study-management/study-management-edit/population-details/population-details.module.ts
> +    TranslateModule
We have lots of common modules such as TranslateModule. Maybe, we can import and export them in the shared module and just use it in other modules. Or we can create another module named CommonModule and do the same thing.

2024-06-25 11:54 UTC, dogukan10 commented on src/app/modules/study-management/study-management-edit/study-details/study-details.component.ts
> +      const name = this.selectedStudy.name ?? '';
Can we get rid of these redundant variables ?

2024-06-25 11:54 UTC, dogukan10 commented on src/app/modules/study-management/study-management-edit/population-details/population-details.component.ts
> +    const populationUrl = this.selectedPopulation.populationUrl ?? '';
Remove redundant variables

2024-06-25 11:54 UTC, dogukan10 commented on src/app/core/services/survey.service.ts
> +                    console.log(error);
I think we should not use console.log. If you want to print the error, you can use console.error. However, we can skip the logging.

2024-06-25 11:58 UTC, dogukan10 commented
Here, we can assign one of the following roles:

- Study Owner
- Survey Manager
- Data Engineer
- Data Scientiest
- ML Engineer
- Quality Assurance Specialist

![image](https://github.com/AI4HF/passport-web/assets/30176031/6c4c5ffe-d3d8-4924-8966-50ce484205c5)

2024-06-25 12:13 UTC, postaci commented on src/app/modules/study-management/study-management-edit/population-details/population-details.module.ts
> +export class PopulationDetailsModule { }
This is possible and essentially correct but this approach might lead to larger monolithic modules which can become harder to maintain as the application grows. Breaking functionalities into small modules increases modularity, maintainability, reusability and testing. Each submodule can later be reused in different modules as well without importing the entire parent module.

2024-06-25 12:16 UTC, postaci commented on src/app/shared/components/stepper/stepper.module.ts
> +export class StepperModule { }
You are absolutely correct @dogukan10  but this is up to us I think. An Angular "Shared Module" is supposed to be imported in each module and should provide each functionality (as modules - like TranslateModule, etc.) that will be used by again each module. Some functionalities like StepperModule can still be structured within a "Shared" folder but not in "Shared Module" if it is supposed to be used not by each module but only a few modules, which is OK imho.

2024-06-25 12:18 UTC, postaci commented on src/app/modules/study-management/study-management-edit/population-details/population-details.module.ts
> +    TranslateModule
I agree, TranslateModule (and any other module that is needed by each module) can be organized into a SharedModule which will be consumed by each module but PrimeNG modules should be imported by the module that requires the specific module.

2024-06-26 06:04 UTC, dogukan10 approved these changes

2024-06-26 06:05 UTC, merged