Survey and Organization Management Pages
AI4HF/passport-web pull request #6
Opened 2024-06-24 12:13 UTC by KeremHmd

- Survey Management page is implemented all by itself, with backend support and proper project structure.
- Organization Page implementation is adapted to the new and better project structure.
- Necessary changes are made in other files for adaptation purposes.

2024-06-24 12:49 UTC, Okanmercan99 commented on src/app/core/services/organization.service.ts
> +        const url = `${this.endpoint}/`;
"/" is obsolete.

2024-06-24 13:13 UTC, Okanmercan99 commented on src/app/modules/organization-management/organization/organization-form/organization-form.component.ts
> +export class OrganizationFormComponent extends BaseComponent implements OnInit {
Missing comment.

2024-06-24 13:16 UTC, Okanmercan99 commented on src/app/modules/organization-management/organization/organization-form/organization-form.component.ts
> +        this.route.params.subscribe(params => {
This should be handled by using resolvers. You can see an example resolver in core/resolvers/study-management.resolver.ts

2024-06-24 13:18 UTC, Okanmercan99 commented on src/app/modules/organization-management/organization/organization-form/organization-form.component.ts
> +                        console.log(error);
Let's show error message to the user in toaster by using messageService in BaseComponent.

2024-06-24 13:19 UTC, Okanmercan99 commented on src/app/modules/organization-management/organization/organization-form/organization-form.component.ts
> +export class OrganizationFormComponent extends BaseComponent implements OnInit {
Missing comments in methods of this class.

2024-06-24 13:23 UTC, Okanmercan99 commented on src/app/modules/organization-management/organization/organization-form/organization-form.component.ts
> +                        console.log(error);
Let's apply this pattern into all error handling functions.

2024-06-24 13:25 UTC, Okanmercan99 commented on src/app/modules/organization-management/organization/organization-form/organization-form.component.ts
> +        if (this.organizationForm.valid) {
Let's disable button if organization form is not valid. You do not need to check in the method.

2024-06-24 13:27 UTC, Okanmercan99 commented on src/app/modules/organization-management/organization/organization-form/organization-form.component.ts
> +                const updatedOrganization = { ...this.selectedOrganization, ...this.organizationForm.value };
Let's construct a new Organization object using Organization Class constructor for type safety.

2024-06-24 13:38 UTC, Okanmercan99 commented on src/app/modules/organization-management/organization/organization-routing.module.ts
> +    { path: 'form/new', component: OrganizationFormComponent },
Let's call OrganizationFormComponent in OrganizationTable component using selector of the component. You can pass a display boolean using @input annotation. OrganizationFormComponent do not need routing.

2024-06-24 13:44 UTC, Okanmercan99 commented on src/app/modules/organization-management/organization/organization-table/organization-table.component.ts
> +export class OrganizationTableComponent extends BaseComponent implements OnInit {
Missing class comment and method comments.

2024-06-24 14:15 UTC, Okanmercan99 commented on src/app/modules/organization-management/organization/organization-table/organization-table.component.ts
> +        this.organizationService.getAllOrganizations().pipe(takeUntil(this.destroy$)).subscribe({
Why do we fetch all organization and select first one?

2024-06-24 14:20 UTC, Okanmercan99 commented on src/app/modules/organization-management/organization/organization-table/organization-table.component.ts
> +        this.organizationService.deleteOrganization(<number><unknown>localStorage.getItem('organizationId')).pipe(takeUntil(this.destroy$)).subscribe({
Let's do not typecast like this

2024-06-24 14:23 UTC, Okanmercan99 commented on src/app/modules/organization-management/personnel/personnel-form/personnel-form.component.ts
> +export class PersonnelFormComponent extends BaseComponent implements OnInit {
Missing class and method comments.

2024-06-24 14:25 UTC, Okanmercan99 commented on src/app/modules/organization-management/personnel/personnel-form/personnel-form.component.ts
> +        this.route.params.subscribe(params => {
Let's implement a personnel resolver for here.

2024-06-24 14:36 UTC, Okanmercan99 commented on src/app/modules/organization-management/personnel/personnel-form/personnel-form.component.ts
> +            const updatedPersonnel = {...this.selectedPersonnel, ...this.personnelForm.value};
Let's construct a valid Personnel object here.

2024-06-24 14:37 UTC, Okanmercan99 commented on src/app/modules/organization-management/personnel/personnel-form/personnel-form.component.ts
> +            const newPersonnel = {...this.personnelForm.value, organizationId: <number><unknown>organizationId};
Also here construct valid personnel object. You should not typecast like this.

2024-06-24 14:38 UTC, Okanmercan99 commented on src/app/modules/organization-management/personnel/personnel-routing.module.ts
> +    { path: 'form/new', component: PersonnelFormComponent },
Like in Organization form, personnel form should not have a routing.

2024-06-25 06:24 UTC, Okanmercan99 commented on src/app/modules/organization-management/personnel/personnel-table/personnel-table.component.ts
> +export class PersonnelTableComponent extends BaseComponent implements OnInit {
Missing class and method comments.

2024-06-25 06:29 UTC, Okanmercan99 commented on src/app/modules/survey-management/survey-management-form/survey-management-form.component.html
> +<p-dialog [(visible)]="displayDialog" [modal]="true" header="Question Form" (onHide)="closeDialog()">
Let's use translation service in header.

2024-06-25 06:30 UTC, Okanmercan99 commented on src/app/modules/survey-management/survey-management-form/survey-management-form.component.html
> +    <button (click)="saveQuestion()" icon="pi pi-check" label="Save" pButton type="button"></button>
Let's use translation service in button labels also.

2024-06-25 06:32 UTC, Okanmercan99 commented on src/app/modules/survey-management/survey-management-form/survey-management-form.component.ts
> +    selectedQuestion: Survey = new Survey({});
Missing comments in the component fields.

2024-06-25 07:09 UTC, Okanmercan99 commented on src/app/shared/models/organization.model.ts
> +export class Organization {
Missing comment

2024-07-03 12:31 UTC, Okanmercan99 submitted a review, later dismissed

2024-07-03 12:31 UTC, Okanmercan99 commented on src/app/modules/organization-management/personnel/personnel-routing.module.ts
> +    { path: 'table', component: PersonnelTableComponent }
Same as organization-routing, lets give empty string path.

2024-07-03 12:31 UTC, Okanmercan99 commented on src/app/modules/organization-management/personnel/personnel-table/personnel-table.component.ts
> +        const organizationId = this.organizationStateService.getOrganizationId();
Let's get organizationId as subcription based. Maybe you can move this logic into subcription below.

2024-07-03 12:31 UTC, Okanmercan99 commented on src/app/modules/organization-management/personnel/personnel-table/personnel-table.component.ts
> +                this.loading = false;
Let's move this.loading = false statement into complete field. Subcribe function can take { next, error, complete } objects.

2024-07-03 12:31 UTC, Okanmercan99 commented on src/app/modules/organization-management/personnel/personnel-table/personnel-table.component.ts
> +                this.loading = false;
Let's handle error case appropriately by using messageService and toasters.

2024-07-03 12:31 UTC, Okanmercan99 commented on src/app/shared/models/organization.model.ts
> +    constructor(data: any) {
Please add null check before accessing data fields. You can refer other model constructors.

2024-07-04 13:01 UTC, dogukan10 requested changes

2024-07-04 13:01 UTC, dogukan10 commented on src/app/modules/survey-management/survey-management-form/survey-management-form.component.ts
> +        if (this.studies.length === 0) {
Add comments to these if statements so that we can easily understand the possible use cases here.

2024-07-04 14:04 UTC, dogukan10 approved these changes

2024-07-04 14:04 UTC, dogukan10 commented on src/app/core/guards/auth.interceptor.ts
> +                if (error.status === 401) {
Will be resolved in another branch.

2024-07-04 14:04 UTC, dogukan10 commented on src/app/modules/login/login.component.ts
> +    checkRememberedUser() {
Will be resolved in another branch.

2024-07-04 14:05 UTC, dogukan10 commented on src/app/modules/login/login.component.ts
> +            localStorage.setItem('token', token);
Will be resolved in another branch.

2024-07-04 14:05 UTC, dogukan10 commented on src/app/modules/login/login.component.ts
> +        if (rememberMe) {
Will be resolved in another branch.

2024-07-04 14:13 UTC, merged