Data Management - Feature and Dataset Management Pages
AI4HF/passport-web pull request #9
Opened 2024-07-18 14:27 UTC by KeremHmd

- Feature and Dataset Management Pages are implemented with proper backend connections.
- Few other forms have been updated with new design choices.

2024-07-22 08:28 UTC, Okanmercan99 requested changes

2024-07-22 08:28 UTC, Okanmercan99 commented on src/app/modules/data-engineer-page/dataset-management/dataset-management-edit/learning-dataset-creation/learning-dataset-creation-form/learning-dataset-creation-form.component.ts
> +    @Input() transformation: DatasetTransformation;
Let's pass Transformation id and fetch from API in this module.

2024-07-22 08:28 UTC, Okanmercan99 commented on src/app/modules/data-engineer-page/featureset-management/featureset-management-edit/featureset-details/featureset-details.component.html
> +                <p-dropdown
Experiment dropdown is not selected although selected featureSet has experiment information.

2024-07-22 08:28 UTC, Okanmercan99 commented on src/app/modules/data-engineer-page/featureset-management/featureset-management-edit/featureset-features/featureset-features-form/featureset-features-form.component.ts
> +    @Input() feature: Feature;
Let's pass featureId and fetch feature information from the API.

2024-07-22 08:28 UTC, Okanmercan99 commented on src/app/shared/models/dataset.model.ts
> +export class Dataset {
Missing comments.

2024-07-22 08:28 UTC, Okanmercan99 commented on src/app/shared/models/datasetCharacteristic.model.ts
> +export class DatasetCharacteristic {
Missing comments.

2024-07-22 08:28 UTC, Okanmercan99 commented on src/app/shared/models/datasetTransformation.model.ts
> +export class DatasetTransformation {
Missing comments.

2024-07-22 08:28 UTC, Okanmercan99 commented on src/app/shared/models/datasetTransformationStep.model.ts
> +export class DatasetTransformationStep {
Missing comments.

2024-07-22 08:28 UTC, Okanmercan99 commented on src/app/shared/models/feature.model.ts
> +export class Feature {
Missing comments.

2024-07-22 08:28 UTC, Okanmercan99 commented on src/app/shared/models/featureset.model.ts
> +export class FeatureSet {
missing comments.

2024-07-22 08:28 UTC, Okanmercan99 commented on src/app/shared/models/learningDataset.model.ts
> +export class LearningDataset {
missing comments.

2024-07-26 06:43 UTC, Okanmercan99 requested changes

2024-07-26 06:43 UTC, Okanmercan99 commented on src/app/modules/dataset-management/dataset-management-edit/learning-dataset-creation/learning-dataset-creation-table/learning-dataset-creation-table.component.ts
> +                });
Let's add error handling here.

2024-07-26 06:43 UTC, Okanmercan99 commented on src/app/modules/dataset-management/dataset-management-edit/learning-dataset-creation/learning-dataset-creation-table/learning-dataset-creation-table.component.ts
> +                    this.learningDatasets = this.learningDatasets.filter(ld => ld.learningDatasetId !== learningDataset.learningDatasetId);
Let's drop out datasetTransformations related to deleted learningDataset

2024-07-26 06:43 UTC, Okanmercan99 commented on src/app/modules/featureset-management/featureset-management-edit/featureset-features/featureset-features-form/featureset-features-form.component.html
> +<p-dialog (onHide)="closeDialog()" [(visible)]="this.display" [modal]="true" [style]="{width: '80rem'}" header="{{ 'FeatureSetManagement.Feature Form' | translate }}">
Let's add FeatureSetManagement.Feature Form definition into i18n file.

2024-07-30 08:34 UTC, Okanmercan99 requested changes

2024-07-31 08:17 UTC, Okanmercan99 approved these changes

2024-07-31 10:25 UTC, dogukan10 approved these changes

2024-07-31 10:25 UTC, merged